version: '3.9'   # Version de la syntaxe Docker Compose

services:        # Définition des services (chaque conteneur = 1 service)

  backend:       # Service du back-end (Flask)
    build:
      context: ./back-end   # Dossier contenant le Dockerfile du back-end
      dockerfile: Dockerfile
    container_name: backend_container   # Nom du conteneur (optionnel)
    ports:
      - "5252:5252"   # Port hôte:port conteneur → API dispo sur http://localhost:5252

  frontend:      # Service du front-end (Nginx)
    build:
      context: ./front-end   # Dossier contenant le Dockerfile du front-end
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "9000:9000"   # Front accessible sur http://localhost:9000
    depends_on:       # Le front attend que le back démarre avant de se lancer
      - backend
