# Basé sur la dernière version de Ubuntu
FROM ubuntu:latest

# Mise à jour APT à l'aide de la commande apt-get update
RUN apt-get update

# Mettre à niveau les logiciels actuellement installés via APT à l'aide de la commande apt-get upgrade -y
RUN apt-get upgrade -y

# Imprime "Hello, World!" dans le terminal
CMD ["echo", "Hello, World!"]
